import 'package:flutter_test/flutter_test.dart';
import 'package:streampath/core/utils/strm_parser.dart';

void main() {
  group('parseStrmUrl', () {
    test('标准单行 URL', () {
      expect(parseStrmUrl('http://nas.example.com/dav/movie.mkv\n'),
          'http://nas.example.com/dav/movie.mkv');
    });

    test('前导/尾随空白被裁剪', () {
      expect(parseStrmUrl('  http://nas.example.com/dav/a.mp4  \n'),
          'http://nas.example.com/dav/a.mp4');
    });

    test('跳过空行与 # 注释行，取首个有效行', () {
      const content = '\n# generated by emby\nhttp://nas.example.com/dav/b.mkv\n';
      expect(parseStrmUrl(content), 'http://nas.example.com/dav/b.mkv');
    });

    test('无有效内容返回 null', () {
      expect(parseStrmUrl(''), isNull);
      expect(parseStrmUrl('\n\n# comment only\n'), isNull);
      expect(parseStrmUrl('   \n'), isNull);
    });

    test('剥离 UTF-8 BOM 前缀', () {
      expect(parseStrmUrl('\uFEFFhttp://nas.example.com/dav/movie.mkv\n'),
          'http://nas.example.com/dav/movie.mkv');
    });

    test('支持相对路径形式（由上层拼接绝对地址）', () {
      expect(parseStrmUrl('/dav/movie.mkv\n'), '/dav/movie.mkv');
    });
  });
}
