import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../../data/models/app_language.dart';
import 'app_translation_catalog.dart';

/// StreamPath 项目文案的本地化入口。
class AppLocalizations {
  const AppLocalizations(this.language);

  final AppLanguage language;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations) ??
      const AppLocalizations(AppLanguage.simplifiedChinese);

  String text(String source) {
    final translations = switch (language) {
      AppLanguage.simplifiedChinese => null,
      AppLanguage.traditionalChinese => traditionalChineseTranslations,
      AppLanguage.japanese => japaneseTranslations,
      AppLanguage.english => englishTranslations,
    };
    return _supplementalTranslations[language]?[source] ??
        translations?[source] ??
        _translateDynamic(source, translations);
  }

  String format(String source, Map<String, Object?> arguments) {
    var result = text(source);
    for (final argument in arguments.entries) {
      result = result.replaceAll(
        '{${argument.key}}',
        '${argument.value ?? ''}',
      );
    }
    return result;
  }

  String _translateDynamic(String source, Map<String, String>? translations) {
    if (translations == null) return source;
    var result = source;
    for (final fragment in _dynamicFragments) {
      final translated =
          _supplementalTranslations[language]?[fragment] ??
          translations[fragment];
      if (translated != null && result.contains(fragment)) {
        result = result.replaceAll(fragment, translated);
      }
    }
    return result;
  }

  static const List<String> _dynamicFragments = <String>[
    '读取本地蓝光续播记录失败：',
    '本地蓝光已暂停：',
    '正在播放本地蓝光：',
    '继续播放本地蓝光：',
    '重新连接失败：',
    '无法启动播放器「',
    '」：文件不存在或路径错误',
    '播放器启动失败：',
    '播放器文件不存在：',
    '公开设置接口返回 code ',
    '公开设置接口返回 HTTP ',
    '认证或网络请求失败：',
    '公开设置接口请求失败：',
    '写入检查失败：',
    '索引搜索失败：',
    '读取索引状态失败：',
    '无法读取索引状态：',
    '索引更新未启动：',
    '无法读取当前用户根路径：',
    '无法读取最大索引深度：',
    '读取 OpenList/AList 能力失败：',
    '索引搜索不可用：当前后台缺少 ',
    '索引状态不可用：当前后台缺少 ',
    '索引增量更新不可用：当前后台缺少 ',
    '存储恢复不可用：当前后台缺少 ',
    ' 端点',
    '；不会回退为全量构建',
    '；已禁止提交索引更新',
    '普通用户登录请求异常：',
    '管理员登录请求异常：',
    '普通用户登录失败：',
    '管理员登录失败：',
    '请先关闭或删除一个音频下边栏后再播放。',
    '请先关闭或删除一个下边栏后再播放。',
    '」：strm 内容无效或读取失败',
    '当前最多同时保留 ',
    ' 个音频会话，',
    ' 个播放会话，',
    '已启动音频播放器（',
    '已启动播放器（',
    '数据库维护完成，已创建 ',
    ' 个备份',
    '无法播放「',
    '诊断执行失败：',
    '导出诊断包失败：',
    '脱敏诊断包已导出：',
    '保存收藏失败：',
    '保存最近播放失败：',
    '保存最近目录失败：',
    '读取媒体资产失败：',
    '连接失败：',
    '清空最近播放失败：',
    '清空最近目录失败：',
    '清理缓存失败：',
    '清理媒体中心记录失败：',
    '清理学习数据失败：',
    '删除最近播放失败：',
    '删除最近目录失败：',
    '刷新媒体资产失败：',
    '索引更新失败：',
    'Windows 外观能力检测失败：',
    '上次更新时间：',
    '上次错误：',
    '已处理条目：',
    '应用窗口外观失败：',
    '重置设置失败：',
    '正在播放：',
    '正在播放音频：',
    '正在播放 ISO：',
    '正在打开：',
    '正在打开音频：',
    '正在打开 ISO：',
    '正在恢复：',
    '继续播放：',
    '继续播放音频：',
    '继续播放 ISO：',
    '音频已暂停：',
    'ISO 已暂停：',
    '已暂停：',
    '字幕：',
    '封面：',
    '歌词：',
    '状态：',
    '续播于 ',
    ' 集）',
    ' 首）',
    '已播放 ',
  ];

  static const Map<AppLanguage, Map<String, String>>
  _supplementalTranslations = <AppLanguage, Map<String, String>>{
    AppLanguage.traditionalChinese: <String, String>{
      '数据展示模式': '資料顯示模式',
      '各来源独立': '各來源獨立',
      '本地挂载文件夹共享': '本機掛載資料夾共用',
      '本地与网络存储共享': '本機與網路儲存空間共用',
      '语言': '語言',
      '界面语言': '介面語言',
      '选择软件使用的显示语言；保存全部配置后立即切换。': '選擇軟體使用的顯示語言；儲存全部設定後立即切換。',
      '连接失败：': '連線失敗：',
      '保存收藏失败：': '儲存收藏失敗：',
      '保存最近播放失败：': '儲存最近播放失敗：',
      '保存最近目录失败：': '儲存最近目錄失敗：',
      '读取媒体资产失败：': '讀取媒體資產失敗：',
      '清空最近播放失败：': '清空最近播放失敗：',
      '清空最近目录失败：': '清空最近目錄失敗：',
      '删除最近播放失败：': '刪除最近播放失敗：',
      '删除最近目录失败：': '刪除最近目錄失敗：',
      '刷新媒体资产失败：': '重新整理媒體資產失敗：',
      '清理缓存失败：': '清理快取失敗：',
      '清理媒体中心记录失败：': '清理媒體中心記錄失敗：',
      '清理学习数据失败：': '清理學習資料失敗：',
      '索引更新失败：': '索引更新失敗：',
      'Windows 外观能力检测失败：': 'Windows 外觀能力偵測失敗：',
      '应用窗口外观失败：': '套用視窗外觀失敗：',
      '重置设置失败：': '重設設定失敗：',
      '诊断执行失败：': '執行診斷失敗：',
      '导出诊断包失败：': '匯出診斷包失敗：',
      '脱敏诊断包已导出：': '已匯出去識別化診斷包：',
      '正在播放：': '正在播放：',
      '正在播放音频：': '正在播放音訊：',
      '正在播放 ISO：': '正在播放 ISO：',
      '正在打开：': '正在開啟：',
      '正在打开音频：': '正在開啟音訊：',
      '正在打开 ISO：': '正在開啟 ISO：',
      '正在恢复：': '正在復原：',
      '继续播放：': '繼續播放：',
      '继续播放音频：': '繼續播放音訊：',
      '继续播放 ISO：': '繼續播放 ISO：',
      '已暂停：': '已暫停：',
      '音频已暂停：': '音訊已暫停：',
      'ISO 已暂停：': 'ISO 已暫停：',
      '字幕：': '字幕：',
      '封面：': '封面：',
      '歌词：': '歌詞：',
      '状态：': '狀態：',
      '上次更新时间：': '上次更新時間：',
      '上次错误：': '上次錯誤：',
      '已处理条目：': '已處理項目：',
      '续播于 ': '續播於 ',
      '已播放 ': '已播放 ',
      '当前最多同时保留 ': '目前最多同時保留 ',
      ' 个播放会话，': ' 個播放工作階段，',
      ' 个音频会话，': ' 個音訊工作階段，',
      '请先关闭或删除一个下边栏后再播放。': '請先關閉或刪除一個下方播放列後再播放。',
      '请先关闭或删除一个音频下边栏后再播放。': '請先關閉或刪除一個音訊播放列後再播放。',
      '无法播放「': '無法播放「',
      '」：strm 内容无效或读取失败': '」：strm 內容無效或讀取失敗',
      '已启动播放器（': '已啟動播放器（',
      '已启动音频播放器（': '已啟動音訊播放器（',
      ' 集）': ' 集）',
      ' 首）': ' 首）',
      '数据库维护完成，已创建 ': '資料庫維護完成，已建立 ',
      ' 个备份': ' 個備份',
      '尚不可证明': '無法確認',
      '不可用': '不可用',
      '可用': '可用',
      '请输入 {min}～{max} {unit}': '請輸入 {min}～{max} {unit}',
      '状态：{status}': '狀態：{status}',
      '已处理条目：{count}': '已處理項目：{count}',
      '上次更新时间：{time}': '上次更新時間：{time}',
      '上次错误：{error}': '上次錯誤：{error}',
      '目录、视频、STRM 和音频合计；系统最高 {max} 条': '目錄、影片、STRM 和音訊合計；系統最高 {max} 條',
      '视频、音频各自计算；系统最高 {max} 条': '影片、音訊分別計算；系統最高 {max} 條',
      '当前来源单独计算；系统最高 {max} 条': '目前來源單獨計算；系統最高 {max} 條',
      'Windows {major}.{minor}（内部版本 {build}）':
          'Windows {major}.{minor}（內部版本 {build}）',
      '透明效果：{transparency} · 高对比度：{contrast}':
          '透明效果：{transparency} · 高對比度：{contrast}',
      '排序：{mode} · {direction}': '排序：{mode} · {direction}',
      '未在当前服务器目录中找到「{name}」': '在目前伺服器目錄中找不到「{name}」',
      '{path}  ·  已播放 {duration}': '{path}  ·  已播放 {duration}',
      '{path}  ·  第 {episode}/{total} 集  ·  已播放 {duration}':
          '{path}  ·  第 {episode}/{total} 集  ·  已播放 {duration}',
      '清空 ISO 最近播放？': '清空 ISO 最近播放？',
      '还没有收藏 ISO': '還沒有收藏 ISO',
      '没有可继续播放的 ISO': '沒有可繼續播放的 ISO',
      '还没有 ISO 播放记录': '還沒有 ISO 播放記錄',
      '无法确认 ISO 播放器身份，已保留会话且未终止进程': '無法確認 ISO 播放器身分，已保留工作階段且未終止處理程序',
      '未找到上次播放的 ISO 文件': '找不到上次播放的 ISO 檔案',
      '将清除当前来源的目录、视频、STRM、音频和 ISO 收藏。': '將清除目前來源的目錄、影片、STRM、音訊和 ISO 收藏。',
      '将清除当前来源的视频、音频和 ISO 最近播放记录，并同步移除这些记录在媒体中心的继续播放入口；不会删除底层播放进度。':
          '將清除目前來源的影片、音訊和 ISO 最近播放記錄，並同步移除媒體中心內這些記錄的繼續播放入口；不會刪除底層播放進度。',
      '目录、视频、STRM、音频和 ISO 合计；系统最高 {max} 条':
          '目錄、影片、STRM、音訊和 ISO 合計；系統最高 {max} 條',
      '视频、音频、ISO 各自计算；系统最高 {max} 条': '影片、音訊、ISO 分別計算；系統最高 {max} 條',
      '已开启': '已開啟',
      '已关闭': '已關閉',
      '未开启': '未開啟',
      '尚未读取': '尚未讀取',
      '空闲': '閒置',
      '正在更新': '正在更新',
      '音乐': '音樂',
      '升序': '升冪',
      '降序': '降冪',
      '存储': '儲存空間',
      '网络存储': '網路儲存空間',
      '本地存储': '本機儲存空間',
      '未挂载 WebDAV': '尚未掛載 WebDAV',
      '未挂载本地文件夹': '尚未掛載本機資料夾',
      '已挂载 {count} 个本地文件夹': '已掛載 {count} 個本機資料夾',
      '添加 WebDAV': '新增 WebDAV',
      '无文件': '沒有檔案',
      '添加本地文件夹': '新增本機資料夾',
      '编辑本地文件夹': '編輯本機資料夾',
      '显示名称': '顯示名稱',
      '本地目录': '本機目錄',
      '可直接输入绝对路径，或使用 Windows 目录选择器。': '可直接輸入絕對路徑，或使用 Windows 目錄選擇器。',
      '选择文件夹': '選擇資料夾',
      '选择本地文件夹': '選擇本機資料夾',
      '请输入本地目录': '請輸入本機目錄',
      '本地目录必须是绝对路径': '本機目錄必須是絕對路徑',
      '启用此本地文件夹': '啟用此本機資料夾',
      '删除本地文件夹？': '刪除本機資料夾？',
      '只移除挂载配置，不删除磁盘文件；媒体中心历史将保留为来源不可用。': '只移除掛載設定，不刪除磁碟檔案；媒體中心歷史將保留為來源不可用。',
      '{path} · 已停用': '{path} · 已停用',
      '编辑': '編輯',
      '删除': '刪除',
      '启用': '啟用',
      '停用': '停用',
      '确定': '確定',
      '排序': '排序',
      '本地文件夹挂载与管理': '本機資料夾掛載與管理',
      '本地文件夹': '本機資料夾',
      '可直接输入绝对路径，或使用 Windows 原生目录选择器。删除挂载不会删除磁盘文件。':
          '可直接輸入絕對路徑，或使用 Windows 原生目錄選擇器。刪除掛載不會刪除磁碟檔案。',
      '尚未添加本地文件夹': '尚未新增本機資料夾',
      '无法打开 Windows 文件夹选择器': '無法開啟 Windows 資料夾選擇器',
      '本地根目录不存在或不可访问': '本機根目錄不存在或無法存取',
      '该本地文件夹已停用': '此本機資料夾已停用',
      '无法读取本地目录': '無法讀取本機目錄',
      '本地目录不存在或不可访问': '本機目錄不存在或無法存取',
      '本地文件不存在或不可访问': '本機檔案不存在或無法存取',
      '本地蓝光路径不存在或不可访问': '本機藍光路徑不存在或無法存取',
      '已拒绝指向本地根目录外的路径': '已拒絕指向本機根目錄外的路徑',
      '本地蓝光菜单需要使用 MPV 播放器': '本機藍光選單需要使用 MPV 播放器',
      '请选择 Blu-ray ISO 或有效的 BDMV 文件夹': '請選擇 Blu-ray ISO 或有效的 BDMV 資料夾',
      '所选目录不是有效的 Blu-ray BDMV 根目录': '所選目錄不是有效的 Blu-ray BDMV 根目錄',
      '播放器已启动': '播放器已啟動',
      '音频播放服务尚未初始化': '音訊播放服務尚未初始化',
      '请选择本地 Blu-ray 的播放方式。菜单失败时不会自动切换模式。':
          '請選擇本機 Blu-ray 的播放方式。選單失敗時不會自動切換模式。',
      '主标题模式': '主標題模式',
      '蓝光菜单播放': '藍光選單播放',
      '远程蓝光菜单组件尚未通过能力验证，请使用标题模式': '遠端藍光選單元件尚未通過能力驗證，請使用標題模式',
      '请先安装随附的 WinFsp 运行时，再使用远程蓝光菜单': '請先安裝隨附的 WinFsp 執行環境，再使用遠端藍光選單',
      '安装 WinFsp 运行时': '安裝 WinFsp 執行環境',
      'WinFsp 安装未完成，请重试或使用标题模式': 'WinFsp 安裝未完成，請重試或使用標題模式',
      '当前 MPV 不支持本地蓝光菜单，请选择支持菜单的 MPV': '目前 MPV 不支援本機藍光選單，請選擇支援選單的 MPV',
      '远程蓝光菜单组件已变更，请重新验证能力': '遠端藍光選單元件已變更，請重新驗證能力',
      '当前阶段仅支持 HDMV 菜单，请返回标题模式': '目前階段僅支援 HDMV 選單，請返回標題模式',
      '无法确认菜单类型，请返回标题模式': '無法確認選單類型，請返回標題模式',
      '当前组件不支持远程蓝光菜单': '目前元件不支援遠端藍光選單',
      '此光盘的菜单会话已打开，请先关闭现有会话': '此光碟的選單工作階段已開啟，請先關閉現有工作階段',
      '远程蓝光菜单播放器启动失败，请返回标题模式': '遠端藍光選單播放器啟動失敗，請返回標題模式',
      '请选择 Blu-ray 播放方式。菜单模式仅支持 HDMV，失败时不会自动切换。':
          '請選擇 Blu-ray 播放方式。選單模式僅支援 HDMV，失敗時不會自動切換。',
      '标题/播放列表模式': '標題／播放清單模式',
      '蓝光菜单播放失败': '藍光選單播放失敗',
      '返回选择标题模式': '返回選擇標題模式',
      '本地蓝光播放器已启动': '本機藍光播放器已啟動',
      '本地媒体已移动、删除或来源不可用': '本機媒體已移動、刪除或來源不可用',
      '检测到 Blu-ray BDMV': '偵測到 Blu-ray BDMV',
      '由 MPV/libbluray 显示并控制蓝光菜单': '由 MPV/libbluray 顯示並控制藍光選單',
      '选择播放方式': '選擇播放方式',
      '读取本地蓝光续播记录失败：': '讀取本機藍光續播記錄失敗：',
      '本地蓝光内容已变更，已忽略旧续播位置': '本機藍光內容已變更，已忽略舊續播位置',
      '可继续上次播放的 Title，也可以从头打开菜单或主标题。': '可繼續上次播放的 Title，也可以從頭開啟選單或主標題。',
      '从头打开菜单': '從頭開啟選單',
      '继续上次标题': '繼續上次標題',
      '无法确认对应蓝光播放器进程，未删除播放会话': '無法確認對應的藍光播放器程序，未刪除播放工作階段',
      '本地蓝光已暂停：': '本機藍光已暫停：',
      '正在播放本地蓝光：': '正在播放本機藍光：',
      '继续播放本地蓝光：': '繼續播放本機藍光：',
      '本地蓝光播放服务已关闭': '本機藍光播放服務已關閉',
      '本地蓝光内容已变更，请从头播放': '本機藍光內容已變更，請從頭播放',
      '无法启动播放器「': '無法啟動播放器「',
      '」：文件不存在或路径错误': '」：檔案不存在或路徑錯誤',
      '播放器启动失败：': '播放器啟動失敗：',
      '未配置播放器路径，请先在「设置」中配置': '未設定播放器路徑，請先在「設定」中設定',
      '播放器文件不存在：': '播放器檔案不存在：',
      '重新连接失败：': '重新連線失敗：',
      '公开设置接口可访问': '公開設定介面可存取',
      '公开设置接口未返回 OpenList/AList JSON envelope':
          '公開設定介面未傳回 OpenList/AList JSON envelope',
      '公开设置接口返回 code ': '公開設定介面傳回 code ',
      '公开设置接口返回 HTTP ': '公開設定介面傳回 HTTP ',
      '视频 SQLite': '影片 SQLite',
      '音频 SQLite': '音訊 SQLite',
      '音频进度数据库未初始化': '音訊進度資料庫尚未初始化',
      '目录缓存': '目錄快取',
      'Hive 已打开': 'Hive 已開啟',
      'Hive 尚未初始化': 'Hive 尚未初始化',
      '当前未连接，未执行网络检查': '目前未連線，未執行網路檢查',
      '根目录认证请求成功': '根目錄驗證要求成功',
      '认证或网络请求失败：': '驗證或網路要求失敗：',
      '播放器路径': '播放器路徑',
      '播放器文件不存在': '播放器檔案不存在',
      '播放器文件存在': '播放器檔案存在',
      '播放器可从 PATH 解析': '可從 PATH 解析播放器',
      'PATH 中未找到播放器': 'PATH 中找不到播放器',
      '无法完成 PATH 解析检查': '無法完成 PATH 解析檢查',
      '没有活动 MPV 会话': '沒有作用中的 MPV 工作階段',
      '只读属性查询成功': '唯讀屬性查詢成功',
      '活动会话的 IPC 查询失败': '作用中工作階段的 IPC 查詢失敗',
      '自动恢复未启用': '未啟用自動復原',
      '后台地址无效': '後台位址無效',
      '公开设置接口请求失败：': '公開設定介面要求失敗：',
      '数据目录写入': '資料目錄寫入',
      '创建、刷新与删除测试文件成功': '建立、重新整理及刪除測試檔案成功',
      '写入检查失败：': '寫入檢查失敗：',
      'PRAGMA quick_check 通过': 'PRAGMA quick_check 通過',
      '完整性检查报告异常': '完整性檢查報告異常',
      '配置与迁移': '設定與遷移',
      '配置版本、迁移记录或凭据存在异常': '設定版本、遷移記錄或憑證存在異常',
      '配置版本有效，迁移与凭据状态正常': '設定版本有效，遷移與憑證狀態正常',
      '请先配置有效的 OpenList/AList 后台地址': '請先設定有效的 OpenList/AList 後台位址',
      '普通用户 Token 无效，请填写具有搜索权限的最小权限 Token':
          '一般使用者 Token 無效，請填寫具有搜尋權限的最小權限 Token',
      '索引搜索失败：': '索引搜尋失敗：',
      '索引状态不可用：当前后台缺少 ': '索引狀態不可用：目前後台缺少 ',
      '读取索引状态失败：': '讀取索引狀態失敗：',
      'OpenList/AList 返回了无法识别的索引状态': 'OpenList/AList 傳回無法識別的索引狀態',
      '索引能力探测异常，请检查后台地址和网络连接': '索引能力偵測異常，請檢查後台位址和網路連線',
      '索引更新请求正在处理，请勿重复提交': '索引更新要求正在處理，請勿重複提交',
      '无法读取索引状态：': '無法讀取索引狀態：',
      'OpenList/AList 正在更新索引，本次请求已跳过': 'OpenList/AList 正在更新索引，已略過本次要求',
      '索引增量更新不可用：当前后台缺少 ': '索引增量更新不可用：目前後台缺少 ',
      '索引更新未启动：': '索引更新未啟動：',
      '索引更新已提交，OpenList/AList 将在后台执行': '索引更新已提交，OpenList/AList 將在後台執行',
      '索引更新请求异常，请检查后台地址和网络连接': '索引更新要求異常，請檢查後台位址和網路連線',
      '无法读取当前用户根路径：': '無法讀取目前使用者根路徑：',
      '无法读取最大索引深度：': '無法讀取最大索引深度：',
      '无法解析服务端最大索引深度；已禁止提交索引更新': '無法解析伺服器端最大索引深度；已禁止提交索引更新',
      '读取 OpenList/AList 能力失败：': '讀取 OpenList/AList 能力失敗：',
      '索引搜索不可用：当前后台缺少 ': '索引搜尋不可用：目前後台缺少 ',
      '存储恢复不可用：当前后台缺少 ': '儲存空間復原不可用：目前後台缺少 ',
      ' 端点': ' 端點',
      '；不会回退为全量构建': '；不會回退為完整建置',
      '；已禁止提交索引更新': '；已禁止提交索引更新',
      '未配置普通用户账号密码': '未設定一般使用者帳號密碼',
      '未配置管理员账号密码': '未設定管理員帳號密碼',
      '登录成功': '登入成功',
      '普通用户登录请求异常：': '一般使用者登入要求異常：',
      '管理员登录请求异常：': '管理員登入要求異常：',
      '普通用户账号启用了 2FA，请填写独立的普通用户 Token': '一般使用者帳號已啟用 2FA，請填寫獨立的一般使用者 Token',
      '管理员账号启用了 2FA，请填写独立的管理员 Token': '管理員帳號已啟用 2FA，請填寫獨立的管理員 Token',
      '普通用户登录请求超过总时间限制': '一般使用者登入要求超過總時間限制',
      '管理员登录请求超过总时间限制': '管理員登入要求超過總時間限制',
      '普通用户登录失败：': '一般使用者登入失敗：',
      '管理员登录失败：': '管理員登入失敗：',
    },
    AppLanguage.japanese: <String, String>{
      '数据展示模式': 'データ表示モード',
      '各来源独立': 'ソースごとに独立',
      '本地挂载文件夹共享': 'ローカルフォルダー間で共有',
      '本地与网络存储共享': 'ローカルとネットワーク間で共有',
      '语言': '言語',
      '界面语言': '表示言語',
      '选择软件使用的显示语言；保存全部配置后立即切换。': 'ソフトウェアの表示言語を選択します。すべての設定を保存するとすぐに切り替わります。',
      '连接失败：': '接続に失敗しました：',
      '保存收藏失败：': 'お気に入りの保存に失敗しました：',
      '保存最近播放失败：': '最近の再生履歴の保存に失敗しました：',
      '保存最近目录失败：': '最近のフォルダーの保存に失敗しました：',
      '读取媒体资产失败：': 'メディア項目の読み込みに失敗しました：',
      '清空最近播放失败：': '最近の再生履歴の消去に失敗しました：',
      '清空最近目录失败：': '最近のフォルダーの消去に失敗しました：',
      '删除最近播放失败：': '最近の再生履歴の削除に失敗しました：',
      '删除最近目录失败：': '最近のフォルダーの削除に失敗しました：',
      '刷新媒体资产失败：': 'メディア項目の更新に失敗しました：',
      '清理缓存失败：': 'キャッシュの削除に失敗しました：',
      '清理媒体中心记录失败：': 'メディアセンター履歴の削除に失敗しました：',
      '清理学习数据失败：': '学習データの削除に失敗しました：',
      '索引更新失败：': 'インデックスの更新に失敗しました：',
      'Windows 外观能力检测失败：': 'Windows 外観機能の検出に失敗しました：',
      '应用窗口外观失败：': 'ウィンドウ外観の適用に失敗しました：',
      '重置设置失败：': '設定のリセットに失敗しました：',
      '诊断执行失败：': '診断の実行に失敗しました：',
      '导出诊断包失败：': '診断パッケージのエクスポートに失敗しました：',
      '脱敏诊断包已导出：': '匿名化した診断パッケージをエクスポートしました：',
      '正在播放：': '再生中：',
      '正在播放音频：': '音声を再生中：',
      '正在播放 ISO：': 'ISO を再生中：',
      '正在打开：': '開いています：',
      '正在打开音频：': '音声を開いています：',
      '正在打开 ISO：': 'ISO を開いています：',
      '正在恢复：': '復元中：',
      '继续播放：': '再生を再開：',
      '继续播放音频：': '音声の再生を再開：',
      '继续播放 ISO：': 'ISO の再生を再開：',
      '已暂停：': '一時停止中：',
      '音频已暂停：': '音声を一時停止中：',
      'ISO 已暂停：': 'ISO を一時停止中：',
      '字幕：': '字幕：',
      '封面：': 'カバー：',
      '歌词：': '歌詞：',
      '状态：': '状態：',
      '上次更新时间：': '最終更新日時：',
      '上次错误：': '前回のエラー：',
      '已处理条目：': '処理済み項目：',
      '续播于 ': '再開位置：',
      '已播放 ': '再生済み ',
      '当前最多同时保留 ': '同時に保持できるのは最大 ',
      ' 个播放会话，': ' 件の再生セッションです。',
      ' 个音频会话，': ' 件の音声セッションです。',
      '请先关闭或删除一个下边栏后再播放。': '再生する前に下部バーを閉じるか削除してください。',
      '请先关闭或删除一个音频下边栏后再播放。': '再生する前に音声バーを閉じるか削除してください。',
      '无法播放「': '「',
      '」：strm 内容无效或读取失败': '」を再生できません：strm の内容が無効か、読み込みに失敗しました',
      '已启动播放器（': 'プレーヤーを起動しました（',
      '已启动音频播放器（': '音声プレーヤーを起動しました（',
      ' 集）': ' 話）',
      ' 首）': ' 曲）',
      '数据库维护完成，已创建 ': 'データベースのメンテナンスが完了し、',
      ' 个备份': ' 個のバックアップを作成しました',
      '尚不可证明': '未確認',
      '不可用': '利用不可',
      '可用': '利用可能',
      '请输入 {min}～{max} {unit}': '{min}～{max} {unit}の範囲で入力してください',
      '状态：{status}': '状態：{status}',
      '已处理条目：{count}': '処理済み項目：{count}',
      '上次更新时间：{time}': '最終更新日時：{time}',
      '上次错误：{error}': '前回のエラー：{error}',
      '目录、视频、STRM 和音频合计；系统最高 {max} 条': 'フォルダー、動画、STRM、音声の合計。システム上限は {max} 件です',
      '视频、音频各自计算；系统最高 {max} 条': '動画と音声を個別に集計。システム上限は {max} 件です',
      '当前来源单独计算；系统最高 {max} 条': '現在のソースごとに集計。システム上限は {max} 件です',
      'Windows {major}.{minor}（内部版本 {build}）':
          'Windows {major}.{minor}（ビルド {build}）',
      '透明效果：{transparency} · 高对比度：{contrast}':
          '透明効果：{transparency} · ハイコントラスト：{contrast}',
      '排序：{mode} · {direction}': '並べ替え：{mode} · {direction}',
      '未在当前服务器目录中找到「{name}」': '現在のサーバーフォルダーに「{name}」が見つかりません',
      '{path}  ·  已播放 {duration}': '{path}  ·  再生済み {duration}',
      '{path}  ·  第 {episode}/{total} 集  ·  已播放 {duration}':
          '{path}  ·  第 {episode}/{total} 話  ·  再生済み {duration}',
      '清空 ISO 最近播放？': 'ISO の最近の再生履歴を消去しますか？',
      '还没有收藏 ISO': 'お気に入りの ISO はまだありません',
      '没有可继续播放的 ISO': '再開できる ISO はありません',
      '还没有 ISO 播放记录': 'ISO の再生履歴はまだありません',
      '无法确认 ISO 播放器身份，已保留会话且未终止进程':
          'ISO プレーヤーを確認できないため、セッションを保持し、プロセスを終了しませんでした',
      '未找到上次播放的 ISO 文件': '前回再生した ISO ファイルが見つかりません',
      '将清除当前来源的目录、视频、STRM、音频和 ISO 收藏。':
          '現在のソースのフォルダー、動画、STRM、音声、ISO のお気に入りを消去します。',
      '将清除当前来源的视频、音频和 ISO 最近播放记录，并同步移除这些记录在媒体中心的继续播放入口；不会删除底层播放进度。':
          '現在のソースの動画、音声、ISO の最近の再生履歴とメディアセンターの再開項目を消去します。再生位置は削除しません。',
      '目录、视频、STRM、音频和 ISO 合计；系统最高 {max} 条':
          'フォルダー、動画、STRM、音声、ISO の合計。システム上限は {max} 件です',
      '视频、音频、ISO 各自计算；系统最高 {max} 条': '動画、音声、ISO を個別に集計。システム上限は {max} 件です',
      '已开启': 'オン',
      '已关闭': 'オフ',
      '未开启': 'オフ',
      '尚未读取': '未取得',
      '空闲': '待機中',
      '正在更新': '更新中',
      '音乐': '音楽',
      '升序': '昇順',
      '降序': '降順',
      '存储': 'ストレージ',
      '网络存储': 'ネットワークストレージ',
      '本地存储': 'ローカルストレージ',
      '未挂载 WebDAV': 'WebDAV はマウントされていません',
      '未挂载本地文件夹': 'ローカルフォルダーはマウントされていません',
      '已挂载 {count} 个本地文件夹': '{count} 個のローカルフォルダーをマウント済み',
      '添加 WebDAV': 'WebDAV を追加',
      '无文件': 'ファイルがありません',
      '添加本地文件夹': 'ローカルフォルダーを追加',
      '编辑本地文件夹': 'ローカルフォルダーを編集',
      '显示名称': '表示名',
      '本地目录': 'ローカルフォルダー',
      '可直接输入绝对路径，或使用 Windows 目录选择器。': '絶対パスを直接入力するか、Windows のフォルダー選択を使用できます。',
      '选择文件夹': 'フォルダーを選択',
      '选择本地文件夹': 'ローカルフォルダーを選択',
      '请输入本地目录': 'ローカルフォルダーを入力してください',
      '本地目录必须是绝对路径': 'ローカルフォルダーには絶対パスが必要です',
      '启用此本地文件夹': 'このローカルフォルダーを有効にする',
      '删除本地文件夹？': 'ローカルフォルダーを削除しますか？',
      '只移除挂载配置，不删除磁盘文件；媒体中心历史将保留为来源不可用。':
          'マウント設定のみを削除し、ディスク上のファイルは削除しません。メディアセンターの履歴は利用できないソースとして保持されます。',
      '{path} · 已停用': '{path} · 無効',
      '编辑': '編集',
      '删除': '削除',
      '启用': '有効化',
      '停用': '無効化',
      '确定': 'OK',
      '排序': '並べ替え',
      '本地文件夹挂载与管理': 'ローカルフォルダーのマウントと管理',
      '本地文件夹': 'ローカルフォルダー',
      '可直接输入绝对路径，或使用 Windows 原生目录选择器。删除挂载不会删除磁盘文件。':
          '絶対パスを直接入力するか、Windows 標準のフォルダー選択を使用できます。マウントを削除してもディスク上のファイルは削除されません。',
      '尚未添加本地文件夹': 'ローカルフォルダーはまだ追加されていません',
      '无法打开 Windows 文件夹选择器': 'Windows のフォルダー選択を開けません',
      '本地根目录不存在或不可访问': 'ローカルルートが存在しないか、アクセスできません',
      '该本地文件夹已停用': 'このローカルフォルダーは無効です',
      '无法读取本地目录': 'ローカルフォルダーを読み込めません',
      '本地目录不存在或不可访问': 'ローカルフォルダーが存在しないか、アクセスできません',
      '本地文件不存在或不可访问': 'ローカルファイルが存在しないか、アクセスできません',
      '本地蓝光路径不存在或不可访问': 'ローカル Blu-ray パスが存在しないか、アクセスできません',
      '已拒绝指向本地根目录外的路径': 'ローカルルート外を指すパスを拒否しました',
      '本地蓝光菜单需要使用 MPV 播放器': 'ローカル Blu-ray メニューには MPV が必要です',
      '请选择 Blu-ray ISO 或有效的 BDMV 文件夹': 'Blu-ray ISO または有効な BDMV フォルダーを選択してください',
      '所选目录不是有效的 Blu-ray BDMV 根目录': '選択したフォルダーは有効な Blu-ray BDMV ルートではありません',
      '播放器已启动': 'プレーヤーを起動しました',
      '音频播放服务尚未初始化': '音声再生サービスは初期化されていません',
      '请选择本地 Blu-ray 的播放方式。菜单失败时不会自动切换模式。':
          'ローカル Blu-ray の再生方法を選択してください。メニューに失敗してもモードは自動で切り替わりません。',
      '主标题模式': 'メインタイトルモード',
      '蓝光菜单播放': 'Blu-ray メニューを再生',
      '远程蓝光菜单组件尚未通过能力验证，请使用标题模式': 'リモート Blu-ray メニュー機能は未検証です。タイトルモードをご利用ください',
      '请先安装随附的 WinFsp 运行时，再使用远程蓝光菜单':
          'リモート Blu-ray メニューを使う前に、同梱の WinFsp ランタイムをインストールしてください',
      '安装 WinFsp 运行时': 'WinFsp ランタイムをインストール',
      'WinFsp 安装未完成，请重试或使用标题模式':
          'WinFsp のインストールは完了していません。再試行するかタイトルモードを使用してください',
      '当前 MPV 不支持本地蓝光菜单，请选择支持菜单的 MPV':
          'この MPV はローカル Blu-ray メニューに対応していません。対応する MPV を選択してください',
      '远程蓝光菜单组件已变更，请重新验证能力': 'リモート Blu-ray メニューの構成が変更されました。再検証が必要です',
      '当前阶段仅支持 HDMV 菜单，请返回标题模式': '現段階では HDMV メニューのみ対応しています。タイトルモードに戻ってください',
      '无法确认菜单类型，请返回标题模式': 'メニュー形式を確認できません。タイトルモードに戻ってください',
      '当前组件不支持远程蓝光菜单': '現在のコンポーネントはリモート Blu-ray メニューに対応していません',
      '此光盘的菜单会话已打开，请先关闭现有会话': 'このディスクのメニューは既に開いています。先に終了してください',
      '远程蓝光菜单播放器启动失败，请返回标题模式': 'リモート Blu-ray メニュープレーヤーを起動できません。タイトルモードに戻ってください',
      '请选择 Blu-ray 播放方式。菜单模式仅支持 HDMV，失败时不会自动切换。':
          'Blu-ray の再生方式を選択してください。メニューは HDMV のみ対応し、失敗時に自動切替は行いません。',
      '标题/播放列表模式': 'タイトル／プレイリストモード',
      '蓝光菜单播放失败': 'Blu-ray メニューの再生に失敗しました',
      '返回选择标题模式': 'タイトルモードの選択に戻る',
      '本地蓝光播放器已启动': 'ローカル Blu-ray プレーヤーを起動しました',
      '本地媒体已移动、删除或来源不可用': 'ローカルメディアが移動、削除されたか、ソースを利用できません',
      '检测到 Blu-ray BDMV': 'Blu-ray BDMV を検出しました',
      '由 MPV/libbluray 显示并控制蓝光菜单': 'MPV/libbluray で Blu-ray メニューを表示、操作します',
      '选择播放方式': '再生方法を選択',
      '读取本地蓝光续播记录失败：': 'ローカル Blu-ray の再生履歴を読み込めませんでした：',
      '本地蓝光内容已变更，已忽略旧续播位置': 'ローカル Blu-ray の内容が変更されたため、以前の再生位置を無視しました',
      '可继续上次播放的 Title，也可以从头打开菜单或主标题。':
          '前回の Title を再開するか、メニューまたはメインタイトルを最初から開けます。',
      '从头打开菜单': 'メニューを最初から開く',
      '继续上次标题': '前回のタイトルを再開',
      '无法确认对应蓝光播放器进程，未删除播放会话':
          '対応する Blu-ray プレーヤーのプロセスを確認できないため、再生セッションを削除しませんでした',
      '本地蓝光已暂停：': 'ローカル Blu-ray を一時停止中：',
      '正在播放本地蓝光：': 'ローカル Blu-ray を再生中：',
      '继续播放本地蓝光：': 'ローカル Blu-ray の再生を再開：',
      '本地蓝光播放服务已关闭': 'ローカル Blu-ray 再生サービスは終了しています',
      '本地蓝光内容已变更，请从头播放': 'ローカル Blu-ray の内容が変更されました。最初から再生してください',
      '无法启动播放器「': 'プレーヤーを起動できません「',
      '」：文件不存在或路径错误': '」：ファイルが存在しないか、パスが正しくありません',
      '播放器启动失败：': 'プレーヤーの起動に失敗しました：',
      '未配置播放器路径，请先在「设置」中配置': 'プレーヤーのパスが未設定です。「設定」で設定してください',
      '播放器文件不存在：': 'プレーヤーファイルが存在しません：',
      '重新连接失败：': '再接続に失敗しました：',
      '公开设置接口可访问': '公開設定 API にアクセスできます',
      '公开设置接口未返回 OpenList/AList JSON envelope':
          '公開設定 API が OpenList/AList JSON envelope を返しませんでした',
      '公开设置接口返回 code ': '公開設定 API が code を返しました：',
      '公开设置接口返回 HTTP ': '公開設定 API が HTTP を返しました：',
      '视频 SQLite': '動画 SQLite',
      '音频 SQLite': '音声 SQLite',
      '音频进度数据库未初始化': '音声進捗データベースが初期化されていません',
      '目录缓存': 'フォルダーキャッシュ',
      'Hive 已打开': 'Hive は開いています',
      'Hive 尚未初始化': 'Hive は初期化されていません',
      '当前未连接，未执行网络检查': '未接続のため、ネットワークチェックを実行していません',
      '根目录认证请求成功': 'ルートフォルダーの認証要求に成功しました',
      '认证或网络请求失败：': '認証またはネットワーク要求に失敗しました：',
      '播放器路径': 'プレーヤーのパス',
      '播放器文件不存在': 'プレーヤーファイルが存在しません',
      '播放器文件存在': 'プレーヤーファイルが存在します',
      '播放器可从 PATH 解析': 'PATH からプレーヤーを検出しました',
      'PATH 中未找到播放器': 'PATH にプレーヤーが見つかりません',
      '无法完成 PATH 解析检查': 'PATH の確認を完了できませんでした',
      '没有活动 MPV 会话': 'アクティブな MPV セッションはありません',
      '只读属性查询成功': '読み取り専用プロパティの取得に成功しました',
      '活动会话的 IPC 查询失败': 'アクティブセッションの IPC 問い合わせに失敗しました',
      '自动恢复未启用': '自動復旧は無効です',
      '后台地址无效': 'バックエンドのアドレスが無効です',
      '公开设置接口请求失败：': '公開設定 API の要求に失敗しました：',
      '数据目录写入': 'データフォルダーへの書き込み',
      '创建、刷新与删除测试文件成功': 'テストファイルの作成、更新、削除に成功しました',
      '写入检查失败：': '書き込みチェックに失敗しました：',
      'PRAGMA quick_check 通过': 'PRAGMA quick_check に成功しました',
      '完整性检查报告异常': '整合性チェックで異常が報告されました',
      '配置与迁移': '設定と移行',
      '配置版本、迁移记录或凭据存在异常': '設定バージョン、移行履歴、または資格情報に異常があります',
      '配置版本有效，迁移与凭据状态正常': '設定バージョンは有効で、移行と資格情報は正常です',
      '请先配置有效的 OpenList/AList 后台地址': '有効な OpenList/AList バックエンドアドレスを設定してください',
      '普通用户 Token 无效，请填写具有搜索权限的最小权限 Token':
          '一般ユーザー Token が無効です。検索権限を持つ最小権限の Token を入力してください',
      '索引搜索失败：': 'インデックス検索に失敗しました：',
      '索引状态不可用：当前后台缺少 ': 'インデックス状態を利用できません。バックエンドに次のエンドポイントがありません：',
      '读取索引状态失败：': 'インデックス状態の読み取りに失敗しました：',
      'OpenList/AList 返回了无法识别的索引状态': 'OpenList/AList が認識できないインデックス状態を返しました',
      '索引能力探测异常，请检查后台地址和网络连接':
          'インデックス機能の検出に失敗しました。バックエンドアドレスとネットワーク接続を確認してください',
      '索引更新请求正在处理，请勿重复提交': 'インデックス更新要求を処理中です。重複して送信しないでください',
      '无法读取索引状态：': 'インデックス状態を読み取れません：',
      'OpenList/AList 正在更新索引，本次请求已跳过':
          'OpenList/AList がインデックスを更新中のため、この要求はスキップされました',
      '索引增量更新不可用：当前后台缺少 ': '差分インデックス更新を利用できません。バックエンドに次のエンドポイントがありません：',
      '索引更新未启动：': 'インデックス更新が開始されませんでした：',
      '索引更新已提交，OpenList/AList 将在后台执行':
          'インデックス更新を送信しました。OpenList/AList がバックグラウンドで実行します',
      '索引更新请求异常，请检查后台地址和网络连接': 'インデックス更新要求に失敗しました。バックエンドアドレスとネットワーク接続を確認してください',
      '无法读取当前用户根路径：': '現在のユーザーのルートパスを読み取れません：',
      '无法读取最大索引深度：': '最大インデックス深度を読み取れません：',
      '无法解析服务端最大索引深度；已禁止提交索引更新': 'サーバーの最大インデックス深度を解析できないため、インデックス更新を無効にしました',
      '读取 OpenList/AList 能力失败：': 'OpenList/AList の機能を読み取れません：',
      '索引搜索不可用：当前后台缺少 ': 'インデックス検索を利用できません。バックエンドに次のエンドポイントがありません：',
      '存储恢复不可用：当前后台缺少 ': 'ストレージ復旧を利用できません。バックエンドに次のエンドポイントがありません：',
      ' 端点': ' エンドポイント',
      '；不会回退为全量构建': '。フルビルドにはフォールバックしません',
      '；已禁止提交索引更新': '。インデックス更新を無効にしました',
      '未配置普通用户账号密码': '一般ユーザーのユーザー名とパスワードが未設定です',
      '未配置管理员账号密码': '管理者のユーザー名とパスワードが未設定です',
      '登录成功': 'ログインしました',
      '普通用户登录请求异常：': '一般ユーザーのログイン要求に失敗しました：',
      '管理员登录请求异常：': '管理者のログイン要求に失敗しました：',
      '普通用户账号启用了 2FA，请填写独立的普通用户 Token':
          '一般ユーザーアカウントで 2FA が有効です。専用の一般ユーザー Token を入力してください',
      '管理员账号启用了 2FA，请填写独立的管理员 Token':
          '管理者アカウントで 2FA が有効です。専用の管理者 Token を入力してください',
      '普通用户登录请求超过总时间限制': '一般ユーザーのログイン要求が全体の制限時間を超えました',
      '管理员登录请求超过总时间限制': '管理者のログイン要求が全体の制限時間を超えました',
      '普通用户登录失败：': '一般ユーザーのログインに失敗しました：',
      '管理员登录失败：': '管理者のログインに失敗しました：',
    },
    AppLanguage.english: <String, String>{
      '数据展示模式': 'Data display mode',
      '各来源独立': 'Separate sources',
      '本地挂载文件夹共享': 'Share across local folders',
      '本地与网络存储共享': 'Share local and network storage',
      '语言': 'Language',
      '界面语言': 'Display language',
      '选择软件使用的显示语言；保存全部配置后立即切换。':
          'Choose the display language. It changes after all settings are saved.',
      '连接失败：': 'Connection failed: ',
      '保存收藏失败：': 'Failed to save favorite: ',
      '保存最近播放失败：': 'Failed to save recent playback: ',
      '保存最近目录失败：': 'Failed to save recent directory: ',
      '读取媒体资产失败：': 'Failed to load media items: ',
      '清空最近播放失败：': 'Failed to clear recent playback: ',
      '清空最近目录失败：': 'Failed to clear recent directories: ',
      '删除最近播放失败：': 'Failed to delete recent playback: ',
      '删除最近目录失败：': 'Failed to delete recent directory: ',
      '刷新媒体资产失败：': 'Failed to refresh media items: ',
      '清理缓存失败：': 'Failed to clear cache: ',
      '清理媒体中心记录失败：': 'Failed to clear media center records: ',
      '清理学习数据失败：': 'Failed to clear learning data: ',
      '索引更新失败：': 'Failed to update index: ',
      'Windows 外观能力检测失败：': 'Failed to detect Windows appearance capabilities: ',
      '应用窗口外观失败：': 'Failed to apply window appearance: ',
      '重置设置失败：': 'Failed to reset settings: ',
      '诊断执行失败：': 'Failed to run diagnostics: ',
      '导出诊断包失败：': 'Failed to export diagnostics package: ',
      '脱敏诊断包已导出：': 'Redacted diagnostics package exported: ',
      '正在播放：': 'Playing: ',
      '正在播放音频：': 'Playing audio: ',
      '正在播放 ISO：': 'Playing ISO: ',
      '正在打开：': 'Opening: ',
      '正在打开音频：': 'Opening audio: ',
      '正在打开 ISO：': 'Opening ISO: ',
      '正在恢复：': 'Recovering: ',
      '继续播放：': 'Resume: ',
      '继续播放音频：': 'Resume audio: ',
      '继续播放 ISO：': 'Resume ISO: ',
      '已暂停：': 'Paused: ',
      '音频已暂停：': 'Audio paused: ',
      'ISO 已暂停：': 'ISO paused: ',
      '字幕：': 'Subtitle: ',
      '封面：': 'Cover: ',
      '歌词：': 'Lyrics: ',
      '状态：': 'Status: ',
      '上次更新时间：': 'Last updated: ',
      '上次错误：': 'Last error: ',
      '已处理条目：': 'Processed items: ',
      '续播于 ': 'Resume at ',
      '已播放 ': 'Played ',
      '当前最多同时保留 ': 'You can keep up to ',
      ' 个播放会话，': ' playback sessions at once. ',
      ' 个音频会话，': ' audio sessions at once. ',
      '请先关闭或删除一个下边栏后再播放。':
          'Close or delete a playback bar before playing another item.',
      '请先关闭或删除一个音频下边栏后再播放。':
          'Close or delete an audio bar before playing another item.',
      '无法播放「': 'Unable to play "',
      '」：strm 内容无效或读取失败': '": the strm content is invalid or could not be read',
      '已启动播放器（': 'Player started (',
      '已启动音频播放器（': 'Audio player started (',
      ' 集）': ' episodes)',
      ' 首）': ' tracks)',
      '数据库维护完成，已创建 ': 'Database maintenance completed; created ',
      ' 个备份': ' backups',
      '尚不可证明': 'unconfirmed',
      '不可用': 'unavailable',
      '可用': 'available',
      '请输入 {min}～{max} {unit}': 'Enter a value from {min} to {max} {unit}',
      '状态：{status}': 'Status: {status}',
      '已处理条目：{count}': 'Processed items: {count}',
      '上次更新时间：{time}': 'Last updated: {time}',
      '上次错误：{error}': 'Last error: {error}',
      '目录、视频、STRM 和音频合计；系统最高 {max} 条':
          'Combined folders, videos, STRM files, and audio; system maximum: {max}',
      '视频、音频各自计算；系统最高 {max} 条':
          'Calculated separately for video and audio; system maximum: {max}',
      '当前来源单独计算；系统最高 {max} 条': 'Calculated per source; system maximum: {max}',
      'Windows {major}.{minor}（内部版本 {build}）':
          'Windows {major}.{minor} (build {build})',
      '透明效果：{transparency} · 高对比度：{contrast}':
          'Transparency: {transparency} · High contrast: {contrast}',
      '排序：{mode} · {direction}': 'Sort: {mode} · {direction}',
      '未在当前服务器目录中找到「{name}」':
          'Could not find "{name}" in the current server directory',
      '{path}  ·  已播放 {duration}': '{path}  ·  Played {duration}',
      '{path}  ·  第 {episode}/{total} 集  ·  已播放 {duration}':
          '{path}  ·  Episode {episode}/{total}  ·  Played {duration}',
      '清空 ISO 最近播放？': 'Clear recent ISO playback?',
      '还没有收藏 ISO': 'No favorite ISOs yet',
      '没有可继续播放的 ISO': 'No ISO items to resume',
      '还没有 ISO 播放记录': 'No ISO playback history yet',
      '无法确认 ISO 播放器身份，已保留会话且未终止进程':
          'The ISO player identity could not be confirmed. The session was kept and the process was not terminated',
      '未找到上次播放的 ISO 文件': 'The previously played ISO file could not be found',
      '将清除当前来源的目录、视频、STRM、音频和 ISO 收藏。':
          'Favorites for folders, videos, STRM files, audio, and ISOs in the current source will be cleared.',
      '将清除当前来源的视频、音频和 ISO 最近播放记录，并同步移除这些记录在媒体中心的继续播放入口；不会删除底层播放进度。':
          'Recent video, audio, and ISO playback records for the current source will be cleared together with their media center resume entries. Playback positions will not be deleted.',
      '目录、视频、STRM、音频和 ISO 合计；系统最高 {max} 条':
          'Combined folders, videos, STRM files, audio, and ISOs; system maximum: {max}',
      '视频、音频、ISO 各自计算；系统最高 {max} 条':
          'Calculated separately for video, audio, and ISO; system maximum: {max}',
      '已开启': 'On',
      '已关闭': 'Off',
      '未开启': 'Off',
      '尚未读取': 'Not loaded',
      '空闲': 'Idle',
      '正在更新': 'Updating',
      '音乐': 'Music',
      '升序': 'Ascending',
      '降序': 'Descending',
      '存储': 'Storage',
      '网络存储': 'Network storage',
      '本地存储': 'Local storage',
      '未挂载 WebDAV': 'No WebDAV mounted',
      '未挂载本地文件夹': 'No local folders mounted',
      '已挂载 {count} 个本地文件夹': '{count} local folders mounted',
      '添加 WebDAV': 'Add WebDAV',
      '无文件': 'No files',
      '添加本地文件夹': 'Add local folder',
      '编辑本地文件夹': 'Edit local folder',
      '显示名称': 'Display name',
      '本地目录': 'Local folder',
      '可直接输入绝对路径，或使用 Windows 目录选择器。':
          'Enter an absolute path or use the Windows folder picker.',
      '选择文件夹': 'Choose folder',
      '选择本地文件夹': 'Choose local folder',
      '请输入本地目录': 'Enter a local folder',
      '本地目录必须是绝对路径': 'The local folder must be an absolute path',
      '启用此本地文件夹': 'Enable this local folder',
      '删除本地文件夹？': 'Remove local folder?',
      '只移除挂载配置，不删除磁盘文件；媒体中心历史将保留为来源不可用。':
          'Only the mount is removed. Files stay on disk, and media center history is retained as an unavailable source.',
      '{path} · 已停用': '{path} · Disabled',
      '编辑': 'Edit',
      '删除': 'Delete',
      '启用': 'Enable',
      '停用': 'Disable',
      '确定': 'OK',
      '排序': 'Sort',
      '本地文件夹挂载与管理': 'Mount and manage local folders',
      '本地文件夹': 'Local folders',
      '可直接输入绝对路径，或使用 Windows 原生目录选择器。删除挂载不会删除磁盘文件。':
          'Enter an absolute path or use the native Windows folder picker. Removing a mount does not delete files from disk.',
      '尚未添加本地文件夹': 'No local folders have been added',
      '无法打开 Windows 文件夹选择器': 'Unable to open the Windows folder picker',
      '本地根目录不存在或不可访问': 'The local root does not exist or cannot be accessed',
      '该本地文件夹已停用': 'This local folder is disabled',
      '无法读取本地目录': 'Unable to read the local folder',
      '本地目录不存在或不可访问': 'The local folder does not exist or cannot be accessed',
      '本地文件不存在或不可访问': 'The local file does not exist or cannot be accessed',
      '本地蓝光路径不存在或不可访问':
          'The local Blu-ray path does not exist or cannot be accessed',
      '已拒绝指向本地根目录外的路径': 'A path outside the local root was rejected',
      '本地蓝光菜单需要使用 MPV 播放器': 'Local Blu-ray menus require MPV',
      '请选择 Blu-ray ISO 或有效的 BDMV 文件夹':
          'Choose a Blu-ray ISO or a valid BDMV folder',
      '所选目录不是有效的 Blu-ray BDMV 根目录':
          'The selected folder is not a valid Blu-ray BDMV root',
      '播放器已启动': 'Player started',
      '音频播放服务尚未初始化': 'The audio playback service is not initialized',
      '请选择本地 Blu-ray 的播放方式。菜单失败时不会自动切换模式。':
          'Choose how to play the local Blu-ray. A menu failure will not switch modes automatically.',
      '主标题模式': 'Main title mode',
      '蓝光菜单播放': 'Play Blu-ray menu',
      '远程蓝光菜单组件尚未通过能力验证，请使用标题模式':
          'Remote Blu-ray menus are not yet verified. Use title mode.',
      '请先安装随附的 WinFsp 运行时，再使用远程蓝光菜单':
          'Install the bundled WinFsp runtime before using remote Blu-ray menus.',
      '安装 WinFsp 运行时': 'Install WinFsp runtime',
      'WinFsp 安装未完成，请重试或使用标题模式':
          'WinFsp installation did not complete. Retry or use title mode.',
      '当前 MPV 不支持本地蓝光菜单，请选择支持菜单的 MPV':
          'This MPV does not support local Blu-ray menus. Select a menu-capable MPV.',
      '远程蓝光菜单组件已变更，请重新验证能力':
          'Remote menu components changed. Capability verification is required.',
      '当前阶段仅支持 HDMV 菜单，请返回标题模式':
          'Only HDMV menus are supported at this stage. Return to title mode.',
      '无法确认菜单类型，请返回标题模式':
          'Unable to identify the menu type. Return to title mode.',
      '当前组件不支持远程蓝光菜单':
          'The installed components do not support remote Blu-ray menus.',
      '此光盘的菜单会话已打开，请先关闭现有会话':
          'A menu session for this disc is already open. Close it first.',
      '远程蓝光菜单播放器启动失败，请返回标题模式':
          'The remote menu player failed to start. Return to title mode.',
      '请选择 Blu-ray 播放方式。菜单模式仅支持 HDMV，失败时不会自动切换。':
          'Choose a Blu-ray playback mode. Menus support HDMV only; failures do not switch modes automatically.',
      '标题/播放列表模式': 'Title / playlist mode',
      '蓝光菜单播放失败': 'Blu-ray menu playback failed',
      '返回选择标题模式': 'Return to title selection',
      '本地蓝光播放器已启动': 'Local Blu-ray player started',
      '本地媒体已移动、删除或来源不可用':
          'The local media was moved or deleted, or its source is unavailable',
      '检测到 Blu-ray BDMV': 'Blu-ray BDMV detected',
      '由 MPV/libbluray 显示并控制蓝光菜单':
          'MPV/libbluray displays and controls the Blu-ray menu',
      '选择播放方式': 'Choose playback mode',
      '读取本地蓝光续播记录失败：': 'Failed to read local Blu-ray resume history: ',
      '本地蓝光内容已变更，已忽略旧续播位置':
          'The local Blu-ray content changed. The previous resume position was ignored',
      '可继续上次播放的 Title，也可以从头打开菜单或主标题。':
          'Resume the previous title, or open the menu or main title from the beginning.',
      '从头打开菜单': 'Open menu from beginning',
      '继续上次标题': 'Resume previous title',
      '无法确认对应蓝光播放器进程，未删除播放会话':
          'The Blu-ray player process could not be verified, so the playback session was not removed',
      '本地蓝光已暂停：': 'Local Blu-ray paused: ',
      '正在播放本地蓝光：': 'Playing local Blu-ray: ',
      '继续播放本地蓝光：': 'Resume local Blu-ray: ',
      '本地蓝光播放服务已关闭': 'The local Blu-ray playback service is closed',
      '本地蓝光内容已变更，请从头播放':
          'The local Blu-ray content changed. Start playback from the beginning',
      '无法启动播放器「': 'Unable to start player "',
      '」：文件不存在或路径错误': '": the file does not exist or the path is invalid',
      '播放器启动失败：': 'Player failed to start: ',
      '未配置播放器路径，请先在「设置」中配置':
          'No player path is configured. Configure it in Settings',
      '播放器文件不存在：': 'Player file does not exist: ',
      '重新连接失败：': 'Reconnection failed: ',
      '公开设置接口可访问': 'The public settings endpoint is accessible',
      '公开设置接口未返回 OpenList/AList JSON envelope':
          'The public settings endpoint did not return an OpenList/AList JSON envelope',
      '公开设置接口返回 code ': 'The public settings endpoint returned code ',
      '公开设置接口返回 HTTP ': 'The public settings endpoint returned HTTP ',
      '视频 SQLite': 'Video SQLite',
      '音频 SQLite': 'Audio SQLite',
      '音频进度数据库未初始化': 'The audio progress database is not initialized',
      '目录缓存': 'Directory cache',
      'Hive 已打开': 'Hive is open',
      'Hive 尚未初始化': 'Hive is not initialized',
      '当前未连接，未执行网络检查': 'Not connected; the network check was not run',
      '根目录认证请求成功': 'Root-directory authentication succeeded',
      '认证或网络请求失败：': 'Authentication or network request failed: ',
      '播放器路径': 'Player path',
      '播放器文件不存在': 'Player file does not exist',
      '播放器文件存在': 'Player file exists',
      '播放器可从 PATH 解析': 'Player resolved from PATH',
      'PATH 中未找到播放器': 'Player was not found in PATH',
      '无法完成 PATH 解析检查': 'Unable to complete the PATH resolution check',
      '没有活动 MPV 会话': 'No active MPV session',
      '只读属性查询成功': 'Read-only property query succeeded',
      '活动会话的 IPC 查询失败': 'IPC query failed for the active session',
      '自动恢复未启用': 'Automatic recovery is disabled',
      '后台地址无效': 'The backend address is invalid',
      '公开设置接口请求失败：': 'Public settings endpoint request failed: ',
      '数据目录写入': 'Data-directory write access',
      '创建、刷新与删除测试文件成功': 'Test file creation, flush, and deletion succeeded',
      '写入检查失败：': 'Write check failed: ',
      'PRAGMA quick_check 通过': 'PRAGMA quick_check passed',
      '完整性检查报告异常': 'The integrity check reported a problem',
      '配置与迁移': 'Configuration and migration',
      '配置版本、迁移记录或凭据存在异常':
          'The configuration version, migration history, or credentials are invalid',
      '配置版本有效，迁移与凭据状态正常':
          'The configuration version, migration history, and credentials are valid',
      '请先配置有效的 OpenList/AList 后台地址':
          'Configure a valid OpenList/AList backend address first',
      '普通用户 Token 无效，请填写具有搜索权限的最小权限 Token':
          'The standard-user token is invalid. Enter a least-privilege token with search permission',
      '索引搜索失败：': 'Index search failed: ',
      '索引状态不可用：当前后台缺少 ':
          'Index status is unavailable because the backend is missing ',
      '读取索引状态失败：': 'Failed to read index status: ',
      'OpenList/AList 返回了无法识别的索引状态':
          'OpenList/AList returned an unrecognized index status',
      '索引能力探测异常，请检查后台地址和网络连接':
          'Index capability detection failed. Check the backend address and network connection',
      '索引更新请求正在处理，请勿重复提交': 'An index update request is already being processed',
      '无法读取索引状态：': 'Unable to read index status: ',
      'OpenList/AList 正在更新索引，本次请求已跳过':
          'OpenList/AList is updating the index, so this request was skipped',
      '索引增量更新不可用：当前后台缺少 ':
          'Incremental index updates are unavailable because the backend is missing ',
      '索引更新未启动：': 'Index update did not start: ',
      '索引更新已提交，OpenList/AList 将在后台执行':
          'Index update submitted. OpenList/AList will run it in the background',
      '索引更新请求异常，请检查后台地址和网络连接':
          'Index update request failed. Check the backend address and network connection',
      '无法读取当前用户根路径：': 'Unable to read the current user root path: ',
      '无法读取最大索引深度：': 'Unable to read the maximum index depth: ',
      '无法解析服务端最大索引深度；已禁止提交索引更新':
          'Unable to parse the server maximum index depth; index updates are disabled',
      '读取 OpenList/AList 能力失败：': 'Failed to read OpenList/AList capabilities: ',
      '索引搜索不可用：当前后台缺少 ':
          'Index search is unavailable because the backend is missing ',
      '存储恢复不可用：当前后台缺少 ':
          'Storage recovery is unavailable because the backend is missing ',
      ' 端点': ' endpoint',
      '；不会回退为全量构建': '; a full build will not be used as a fallback',
      '；已禁止提交索引更新': '; index updates are disabled',
      '未配置普通用户账号密码': 'Standard-user credentials are not configured',
      '未配置管理员账号密码': 'Administrator credentials are not configured',
      '登录成功': 'Signed in successfully',
      '普通用户登录请求异常：': 'Standard-user login request failed: ',
      '管理员登录请求异常：': 'Administrator login request failed: ',
      '普通用户账号启用了 2FA，请填写独立的普通用户 Token':
          'The standard-user account uses 2FA. Enter a dedicated standard-user token',
      '管理员账号启用了 2FA，请填写独立的管理员 Token':
          'The administrator account uses 2FA. Enter a dedicated administrator token',
      '普通用户登录请求超过总时间限制':
          'The standard-user login request exceeded the overall time limit',
      '管理员登录请求超过总时间限制':
          'The administrator login request exceeded the overall time limit',
      '普通用户登录失败：': 'Standard-user login failed: ',
      '管理员登录失败：': 'Administrator login failed: ',
    },
  };
}

extension AppLanguagePresentation on AppLanguage {
  Locale get locale => switch (this) {
    AppLanguage.simplifiedChinese => const Locale.fromSubtags(
      languageCode: 'zh',
      scriptCode: 'Hans',
      countryCode: 'CN',
    ),
    AppLanguage.traditionalChinese => const Locale.fromSubtags(
      languageCode: 'zh',
      scriptCode: 'Hant',
      countryCode: 'TW',
    ),
    AppLanguage.japanese => const Locale('ja', 'JP'),
    AppLanguage.english => const Locale('en', 'US'),
  };

  String get nativeLabel => switch (this) {
    AppLanguage.simplifiedChinese => '简体中文',
    AppLanguage.traditionalChinese => '繁體中文',
    AppLanguage.japanese => '日本語',
    AppLanguage.english => 'English',
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      const {'zh', 'ja', 'en'}.contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) => SynchronousFuture(
    AppLocalizations(switch (locale.languageCode) {
      'ja' => AppLanguage.japanese,
      'en' => AppLanguage.english,
      'zh' when locale.scriptCode == 'Hant' || locale.countryCode == 'TW' =>
        AppLanguage.traditionalChinese,
      _ => AppLanguage.simplifiedChinese,
    }),
  );

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
