# RPC 回调可关闭旧 socket 并开始下一条连接，读取循环必须交回事件处理。
set(socket_source "${sp_nfs_SOURCE_DIR}/lib/socket.c")
file(READ "${socket_source}" socket_code)
set(original "        while (1){\n                if (rpc->inpos == 0) {")
set(patched "        while (1){\n                if (!rpc->is_server_context && !rpc->is_connected) {\n                        return 0;\n                }\n                if (rpc->inpos == 0) {")
string(FIND "${socket_code}" "${patched}" patched_position)
if(patched_position EQUAL -1)
  string(FIND "${socket_code}" "${original}" original_position)
  if(original_position EQUAL -1)
    message(FATAL_ERROR "Unexpected libnfs socket read loop")
  endif()
  string(REPLACE "${original}" "${patched}" socket_code "${socket_code}")
  file(WRITE "${socket_source}" "${socket_code}")
endif()

# 取消标记只由拥有上下文的同步等待线程消费，连接也在该线程释放。
set(private_header "${sp_nfs_SOURCE_DIR}/include/libnfs-private.h")
file(READ "${private_header}" private_code)
string(FIND "${private_code}" "sp_cancel_cb" patched_position)
if(patched_position EQUAL -1)
  set(original "       size_t writemax;")
  string(FIND "${private_code}" "${original}" original_position)
  if(original_position EQUAL -1)
    message(FATAL_ERROR "Unexpected libnfs transfer state")
  endif()
  string(REPLACE "${original}" "${original}\n       int (*sp_cancel_cb)(void *);\n       void *sp_cancel_data;" private_code "${private_code}")
  file(WRITE "${private_header}" "${private_code}")
endif()
set(context_source "${sp_nfs_SOURCE_DIR}/lib/libnfs.c")
file(READ "${context_source}" context_code)
string(FIND "${context_code}" "nfs_sync_cancel.inc" patched_position)
if(patched_position EQUAL -1)
  set(marker "void\nnfs_set_poll_timeout(")
  string(FIND "${context_code}" "${marker}" marker_position)
  if(marker_position EQUAL -1)
    message(FATAL_ERROR "Unexpected libnfs polling API")
  endif()
  string(REPLACE "${marker}" "#include \"nfs_sync_cancel.inc\"\n\n${marker}" context_code "${context_code}")
  file(WRITE "${context_source}" "${context_code}")
endif()
set(sync_source "${sp_nfs_SOURCE_DIR}/lib/libnfs-sync.c")
file(READ "${sync_source}" sync_code)
string(FIND "${sync_code}" "sp_cancel_cb" patched_position)
if(patched_position EQUAL -1)
  set(original "\t\tpfd.fd = nfs_get_fd(nfs);")
  string(FIND "${sync_code}" "${original}" original_position)
  if(original_position EQUAL -1)
    message(FATAL_ERROR "Unexpected libnfs synchronous NFS wait")
  endif()
  set(patched "        if (nfs->nfsi->sp_cancel_cb &&\n            nfs->nfsi->sp_cancel_cb(nfs->nfsi->sp_cancel_data)) {\n                rpc_disconnect(nfs->rpc, \"Storage operation cancelled\");\n                rpc_error_all_pdus(nfs->rpc, \"Storage operation cancelled\");\n                break;\n        }\n${original}")
  string(REPLACE "${original}" "${patched}" sync_code "${sync_code}")
  file(WRITE "${sync_source}" "${sync_code}")
endif()

# NFSv4 挂载完成前读取 MAXREAD/MAXWRITE，避免使用未协商的默认块大小。
set(mount_source "${sp_nfs_SOURCE_DIR}/lib/nfs_v4.c")
file(READ "${mount_source}" mount_code)
string(FIND "${mount_code}" "sp_nfs4_query_mount_limits" patched_position)
if(patched_position EQUAL -1)
  set(marker "static void\nnfs4_mount_4_cb(")
  string(FIND "${mount_code}" "${marker}" marker_position)
  set(original "\trpc_set_resiliency(rpc,\n\t\t\t   nfs->nfsi->auto_reconnect,\n\t\t\t   nfs->nfsi->timeout,\n\t\t\t   nfs->nfsi->retrans);\n\n        data->cb(0, nfs, NULL, data->private_data);\n        free_nfs4_cb_data(data);")
  string(FIND "${mount_code}" "${original}" original_position)
  if(marker_position EQUAL -1 OR original_position EQUAL -1)
    message(FATAL_ERROR "Unexpected libnfs NFSv4 mount callback")
  endif()
  set(patched "        if (sp_nfs4_query_mount_limits(nfs, data) < 0) {\n                data->cb(-ENOMEM, nfs, nfs_get_error(nfs), data->private_data);\n                free_nfs4_cb_data(data);\n        }")
  string(REPLACE "${original}" "${patched}" mount_code "${mount_code}")
  string(REPLACE "${marker}" "#include \"nfs4_mount_limits.inc\"\n\n${marker}" mount_code "${mount_code}")
  file(WRITE "${mount_source}" "${mount_code}")
endif()

# LOOKUP 回调已经返回负 errno，OPEN 路径直接保留其分类。
set(open_source "${sp_nfs_SOURCE_DIR}/lib/nfs_v3.c")
file(READ "${open_source}" open_code)
set(original "cb_data->cb(nfsstat3_to_errno(err), nfs,")
set(patched "cb_data->cb(err, nfs,")
string(FIND "${open_code}" "${original}" original_position)
if(NOT original_position EQUAL -1)
  string(REPLACE "${original}" "${patched}" open_code "${open_code}")
  file(WRITE "${open_source}" "${open_code}")
else()
  string(FIND "${open_code}" "${patched}" patched_position)
  if(patched_position EQUAL -1)
    message(FATAL_ERROR "Unexpected libnfs NFSv3 open error callback")
  endif()
endif()
